import 'package:flutter/cupertino.dart';


final List<IconData> myIconList = [
  CupertinoIcons.thermometer_sun,
  CupertinoIcons.ticket,
  CupertinoIcons.tv_circle_fill,
  CupertinoIcons.timer,
  CupertinoIcons.app,
  CupertinoIcons.archivebox,
  CupertinoIcons.arrow_2_circlepath_circle_fill,
  CupertinoIcons.game_controller,
  CupertinoIcons.gauge_badge_minus,
  CupertinoIcons.gear,
  CupertinoIcons.globe,
  CupertinoIcons.gift,
  CupertinoIcons.gobackward,
  CupertinoIcons.goforward,
  CupertinoIcons.add,
  CupertinoIcons.airplane,
  CupertinoIcons.alarm_fill,
  CupertinoIcons.cloud_moon_bolt,
  CupertinoIcons.cloud_bolt,
  CupertinoIcons.cloud_download,
  CupertinoIcons.cloud_drizzle,
  CupertinoIcons.cloud_snow,
  CupertinoIcons.cloud_sun,
  CupertinoIcons.color_filter,
  CupertinoIcons.crop,
  CupertinoIcons.cube,
  CupertinoIcons.delete,
  CupertinoIcons.device_laptop,
  CupertinoIcons.device_phone_landscape,
  CupertinoIcons.device_phone_portrait,
  CupertinoIcons.dial,
  CupertinoIcons.doc_checkmark,
  CupertinoIcons.doc_person,
  CupertinoIcons.dot_radiowaves_left_right,
  CupertinoIcons.dot_square_fill,
  CupertinoIcons.double_music_note,
  CupertinoIcons.download_circle,
  CupertinoIcons.drop,
  CupertinoIcons.ellipses_bubble,
  CupertinoIcons.zzz,
  CupertinoIcons.return_icon,
  CupertinoIcons.rocket_fill,
  CupertinoIcons.search,
  CupertinoIcons.shield,
  CupertinoIcons.shopping_cart,
  CupertinoIcons.slash_circle,
  CupertinoIcons.smoke,
  CupertinoIcons.speaker,
  CupertinoIcons.speaker_slash,
  CupertinoIcons.sportscourt
];

final myIconName = [
  "thermometer sun ",
  "ticket ",
  "tv circle fill ",
  "timer ",
  "app ",
  "archivebox ",
  "arrow 2 circlepath circle fill ",
  "game controller ",
  "gauge badge minus ",
  "gear ",
  "globe ",
  "gift ",
  "gobackward ",
  "goforward ",
  "add ",
  "airplane ",
  "alarm fill ",
  "cloud moon bolt ",
  "cloud bolt ",
  "cloud download ",
  "cloud drizzle ",
  "cloud snow ",
  "cloud sun ",
  "color filter ",
  "crop ",
  "cube ",
  "delete ",
  "device laptop ",
  "device phone landscape ",
  "device phone portrait ",
  "dial ",
  "doc checkmark ",
  "doc person ",
  "dot radiowaves left right ",
  "dot square fill ",
  "double music note ",
  "download circle ",
  "drop ",
  "ellipses bubble ",
  "zzz ",
  "return icon ",
  "rocket fill ",
  "search ",
  "shield ",
  "shopping cart ",
  "slash circle ",
  "smoke ",
  "speaker ",
  "speaker slash ",
  "sportscourt"
];
